# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zencommit < Formula
  desc "Zen Commit - A beautiful conventional commits tool"
  homepage "https://github.com/saivenkatram-git/zencommit"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saivenkatram-git/zencommit/releases/download/v0.2.0/zencommit_0.2.0_darwin_amd64.tar.gz"
      sha256 "9c95bd3b54f680f7debaf32e7de8753539b4ec428354326ad640b20fa6dc18fc"

      def install
        bin.install "zencommit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saivenkatram-git/zencommit/releases/download/v0.2.0/zencommit_0.2.0_darwin_arm64.tar.gz"
      sha256 "379273a2a2f824209c49c2ad5edfad87b2257a707064e159d83f4d191114d396"

      def install
        bin.install "zencommit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saivenkatram-git/zencommit/releases/download/v0.2.0/zencommit_0.2.0_linux_amd64.tar.gz"
      sha256 "62f6c9955971e8ff7278728e7106febd04ad3095d14f36fa0f2f5945cf983395"
      def install
        bin.install "zencommit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saivenkatram-git/zencommit/releases/download/v0.2.0/zencommit_0.2.0_linux_arm64.tar.gz"
      sha256 "93f9efa7833fa04a9bda683a41d597261230b68d5735d33e196264bb8b2ce91f"
      def install
        bin.install "zencommit"
      end
    end
  end

  test do
    system "#{bin}/zencommit", "version"
  end
end
