# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zencommit < Formula
  desc "Zen Commit - A beautiful conventional commits tool"
  homepage "https://github.com/saivenkatram-git/zencommit"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saivenkatram-git/zencommit/releases/download/v0.1.0/zencommit_0.1.0_darwin_amd64.tar.gz"
      sha256 "a54428e125f7b40c96f5c1a51157d355fe42d0266617c8f7aa4e91c5d7c1f320"

      def install
        bin.install "zencommit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saivenkatram-git/zencommit/releases/download/v0.1.0/zencommit_0.1.0_darwin_arm64.tar.gz"
      sha256 "63d78f4bbc5fcfcd0bafc4dcf39cea71f8de8b4e329669d7182dac24b125b031"

      def install
        bin.install "zencommit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saivenkatram-git/zencommit/releases/download/v0.1.0/zencommit_0.1.0_linux_amd64.tar.gz"
      sha256 "9e67658b26964280e22d65212b019475db57f8f13019519a43124fc8d6097302"
      def install
        bin.install "zencommit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saivenkatram-git/zencommit/releases/download/v0.1.0/zencommit_0.1.0_linux_arm64.tar.gz"
      sha256 "f84f3b5d16d80186ee11eb708601bcc8b2ef9fe4fb87723e7739aa8307fc8cb7"
      def install
        bin.install "zencommit"
      end
    end
  end

  test do
    system "#{bin}/zencommit", "version"
  end
end
