# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zencommit < Formula
  desc "Zen Commit - A beautiful conventional commits tool"
  homepage "https://github.com/saivenkatram-git/zencommit"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saivenkatram-git/zencommit/releases/download/v0.1.0/zencommit_0.1.0_darwin_amd64.tar.gz"
      sha256 "85291e48343ed793b95a705c35bca33b64a7c806bfd262235e283d6e79b92d2c"

      def install
        bin.install "zencommit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saivenkatram-git/zencommit/releases/download/v0.1.0/zencommit_0.1.0_darwin_arm64.tar.gz"
      sha256 "704f491a1749cfae33369d84a12acaeeab4a498945a6766878a29d0e6bb8d9d6"

      def install
        bin.install "zencommit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saivenkatram-git/zencommit/releases/download/v0.1.0/zencommit_0.1.0_linux_amd64.tar.gz"
      sha256 "761d14ec023ea7460021874aff333de0c106c8e89f2504e144b2f68caaa5530b"
      def install
        bin.install "zencommit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saivenkatram-git/zencommit/releases/download/v0.1.0/zencommit_0.1.0_linux_arm64.tar.gz"
      sha256 "9d85c055c4c75887d8c278a26fb51bcde63f3487562dc99a1a97531d34b6527f"
      def install
        bin.install "zencommit"
      end
    end
  end

  test do
    system "#{bin}/zencommit", "version"
  end
end
